import Head from 'next/head';
import Footer from '@components/Footer';
import Featured from '@components/Featured';
import Header from '@components/Header';
import { Fragment } from 'react';
import Hero from '@components/Hero';
import client from '../lib/sanity';

export default function Home({ data }) {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main>
        <Hero></Hero>
        <Featured></Featured>
      </main>
      <Footer></Footer>
    </Fragment>
  );
}
